language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install coverage coveralls
script:
  - python module/test_contextpy3.py
after_success:
  - coverage run module/test_contextpy3.py; coveralls